name: Terraform Destroy (API-driven)

on:
  workflow_dispatch:

jobs:
  terraform-destroy-run:
    runs-on: ubuntu-latest

    env:
      TF_API_TOKEN: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }} # TFC API token
      TF_CLOUD_ORGANIZATION: abasista-tfc                    # TFC organization name
      TF_CONFIG_DIR: ./                                      # Path to Terraform files
      TF_WORKSPACE: gha-api-driven-test                      # Workspace name

    defaults:
      run:
        working-directory: ${{ env.TF_CONFIG_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform destroy (plan)
        id: create-destroy-run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          is_destroy: true

      - name: Terraform destroy (apply)
        id: apply-destroy-run 
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.1
        if: ${{ fromJSON(steps.create-destroy-run.outputs.payload).data.attributes.actions.IsConfirmable }}
        with:
          run: ${{ steps.create-destroy-run.outputs.run_id }}
          comment: "Confirming Terraform destroy on ${{ steps.create-destroy-run.outputs.run_id }}"